language: objective-c
osx_image: xcode8.2
xcode_project: Form.xcodeproj
xcode_scheme: Form
xcode_sdk: iphonesimulator10.2

script:
  - xcodebuild clean build test -project "Form.xcodeproj" -scheme "Form" -destination 'platform=iOS Simulator,id=22FA2149-1241-469C-BF6D-462D3837DB72,OS=10.2' | xcpretty -s
