language: objective-c
osx_image: xcode9.3
xcode_project: Form.xcodeproj
xcode_scheme: Form
xcode_sdk: iphonesimulator11.3

script:
  - xcodebuild clean build test -project "Form.xcodeproj" -scheme "Form" -destination 'platform=iOS Simulator,name=iPhone 8,OS=11.3'

after_success:
  - bash <(curl -s https://codecov.io/bash)
  
